
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**************************************************** 
Program Name: Stocks4UGUI.java 
Programmer's Name: Edward Alvarado 
Program Description: This GUI Application takes in stock parameters, stores those stocks into a JList using a stock model and displays the current profit/loss of each stock. 
***********************************************************/

public class Stocks4UGUI extends javax.swing.JFrame {

    // class level refeerences for attributes
    private DefaultListModel<Stock> model;

    /**
     * Creates new form Stocks4UGUI
     */
    public Stocks4UGUI() {
        // create the model for the JList
        model = new DefaultListModel<Stock>();

        initComponents();

        //set form to center of screen
        this.setLocationRelativeTo(null);
        
        //calculate total portfolio value
        calculateTotalValue();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMainTabs = new javax.swing.JTabbedPane();
        pnlStockList = new javax.swing.JPanel();
        scrStocks = new javax.swing.JScrollPane();
        lstStocks = new javax.swing.JList<>();
        lblTotalValue = new javax.swing.JLabel();
        btnRemoveStock = new javax.swing.JButton();
        lblProfitLoss = new javax.swing.JLabel();
        pnlAddStock = new javax.swing.JPanel();
        lblStockName = new javax.swing.JLabel();
        txtStockName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtPurchasePrice = new javax.swing.JTextField();
        lblPurchasePrice = new javax.swing.JLabel();
        txtCurrentPrice = new javax.swing.JTextField();
        lblCurrentPrice = new javax.swing.JLabel();
        btnAddStock = new javax.swing.JButton();
        mnbMainMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniOpen = new javax.swing.JMenuItem();
        mniSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stocks4U App");

        jtpMainTabs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lstStocks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lstStocks.setModel(model);
        lstStocks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstStocksValueChanged(evt);
            }
        });
        scrStocks.setViewportView(lstStocks);

        lblTotalValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalValue.setText("Total Value:");

        btnRemoveStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRemoveStock.setText("Remove Stock");
        btnRemoveStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStockActionPerformed(evt);
            }
        });

        lblProfitLoss.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblProfitLoss.setText("Profit / Loss");

        javax.swing.GroupLayout pnlStockListLayout = new javax.swing.GroupLayout(pnlStockList);
        pnlStockList.setLayout(pnlStockListLayout);
        pnlStockListLayout.setHorizontalGroup(
            pnlStockListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockListLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(btnRemoveStock)
                .addGap(213, 213, 213))
            .addGroup(pnlStockListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStockListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrStocks)
                    .addGroup(pnlStockListLayout.createSequentialGroup()
                        .addGroup(pnlStockListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfitLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlStockListLayout.setVerticalGroup(
            pnlStockListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrStocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProfitLoss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveStock)
                .addGap(18, 18, 18)
                .addComponent(lblTotalValue)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jtpMainTabs.addTab("List", pnlStockList);

        lblStockName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStockName.setText("Stock Name:");

        txtStockName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantity.setText("Quantity:");

        txtPurchasePrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblPurchasePrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPurchasePrice.setText("Purchase Price: ");

        txtCurrentPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblCurrentPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCurrentPrice.setText("Current Price: ");

        btnAddStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddStock.setText("Add Stock");
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddStockLayout = new javax.swing.GroupLayout(pnlAddStock);
        pnlAddStock.setLayout(pnlAddStockLayout);
        pnlAddStockLayout.setHorizontalGroup(
            pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStockLayout.createSequentialGroup()
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addComponent(lblCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addComponent(lblPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addComponent(lblStockName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 174, Short.MAX_VALUE))
            .addGroup(pnlAddStockLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnAddStock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddStockLayout.setVerticalGroup(
            pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStockLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockName)
                    .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPurchasePrice)
                    .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentPrice)
                    .addComponent(txtCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddStock)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jtpMainTabs.addTab("Add Stock", pnlAddStock);

        mnuFile.setText("File");

        mniOpen.setText("Open");
        mniOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mniOpen);

        mniSave.setText("Save");
        mniSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveActionPerformed(evt);
            }
        });
        mnuFile.add(mniSave);
        mnuFile.add(jSeparator1);

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        mnbMainMenu.add(mnuFile);

        setJMenuBar(mnbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
        //verify that fields are complete
        
        if (txtStockName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Stock name is required", "Error. Missing Information", JOptionPane.ERROR_MESSAGE);
            txtStockName.requestFocus();
            return; // end method
        }

        if (txtQuantity.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Quantity is required", "Error. Missing Information", JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return; // end method
        }
        if(txtPurchasePrice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Purchase Price is required", "Error. Missing Information", JOptionPane.ERROR_MESSAGE);
            txtPurchasePrice.requestFocus();
            return; // end method
        }        
        if(txtCurrentPrice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Current Price is required", "Error. Missing Information", JOptionPane.ERROR_MESSAGE);
            txtCurrentPrice.requestFocus();
            return; // end method
        }
        double quantity = 0.0;
        try {
           quantity =  Double.parseDouble(txtQuantity.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid input. Please use numbers only.", "Error. Invalid data", JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return; // end method
        }        
        
        double purchasePrice = 0.0;
        try {
            purchasePrice = Double.parseDouble(txtPurchasePrice.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid input. Please use numbers only.", "Error. Invalid data", JOptionPane.ERROR_MESSAGE);
            txtPurchasePrice.requestFocus();
            return; // end method
        }
        
        double currentPrice = 0.0;
        try {
            currentPrice = Double.parseDouble(txtCurrentPrice.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid input. Please use numbers only.", "Error. Invalid data", JOptionPane.ERROR_MESSAGE);
            txtCurrentPrice.requestFocus();
            return; // end method
        }        
        
        // get input
        String stockName = txtStockName.getText();     
        
        // create the stock object
        Stock stk = new Stock(stockName, quantity, purchasePrice, currentPrice);
        // add the Stock object to the JList's model
        model.addElement(stk);
        //update total value
        calculateTotalValue();
        
        //reset form for the next stock
        txtStockName.setText("");
        txtQuantity.setText("");
        txtPurchasePrice.setText("");
        txtCurrentPrice.setText("");
        txtStockName.requestFocus();

    }//GEN-LAST:event_btnAddStockActionPerformed

    private void lstStocksValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstStocksValueChanged
        // get stockl and show the current profit/loss
        Stock stk = lstStocks.getSelectedValue();
        
        if(stk != null){
            double profitLoss = stk.getProfitLoss();
            DecimalFormat fmt = new DecimalFormat("#,##0.00");
            if(profitLoss > 0.0)
                lblProfitLoss.setText("Profit of "+ fmt.format(profitLoss));
            else if(profitLoss < 0.0)
                lblProfitLoss.setText("Loss of " + fmt.format(profitLoss));
            else
                lblProfitLoss.setText("Break-Even with zero profit/loss");
        }
    }//GEN-LAST:event_lstStocksValueChanged

    private void btnRemoveStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStockActionPerformed
        // get stock position 
        int position = lstStocks.getSelectedIndex();
        
        // if selected, remove the stock
        if(position >= 0){
            model.remove(position);
            lblTotalValue.setText("Profit / Loss");
        //update total value
        calculateTotalValue();        
        }
    }//GEN-LAST:event_btnRemoveStockActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // Exits application
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveActionPerformed
        // get file name
        String fileName = JOptionPane.showInputDialog("Enter filename: ");
        
        
        // save data to the file
        StockIO outToFile = new StockIO(fileName);
        
        ArrayList<Stock> data = new ArrayList<Stock>();
        
        for(int i = 0; i < model.size();i++){
            Stock stk = model.elementAt(i);
            data.add(stk);
        }
        
        outToFile.saveData(data);
        JOptionPane.showMessageDialog(this, "Data was saved to the file!");
    }//GEN-LAST:event_mniSaveActionPerformed

    private void mniOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOpenActionPerformed
        //  get the file name
        String fileName = JOptionPane.showInputDialog("Enter filename: ");
        
        // get data from the file
        StockIO inFromFile = new StockIO(fileName);
        
        ArrayList<Stock> data = inFromFile.getData();
        
        //clear the model and then copy the new data to the model
        model.clear();
        for(int i =0; i<data.size();i++){
            Stock stk = data.get(i);
            model.addElement(stk);
        }
        calculateTotalValue();
    }//GEN-LAST:event_mniOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stocks4UGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stocks4UGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stocks4UGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stocks4UGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stocks4UGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnRemoveStock;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jtpMainTabs;
    private javax.swing.JLabel lblCurrentPrice;
    private javax.swing.JLabel lblProfitLoss;
    private javax.swing.JLabel lblPurchasePrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStockName;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JList<Stock> lstStocks;
    private javax.swing.JMenuBar mnbMainMenu;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenuItem mniSave;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JPanel pnlAddStock;
    private javax.swing.JPanel pnlStockList;
    private javax.swing.JScrollPane scrStocks;
    private javax.swing.JTextField txtCurrentPrice;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStockName;
    // End of variables declaration//GEN-END:variables

    private void calculateTotalValue() {
        //calculates total value of stocks
        double totalValue = 0.0;
        
        // go through each stock in portfolio and calculate the total value
        for(int i = 0;i<model.size();i++){
            Stock stk = model.elementAt(i);
            totalValue += stk.getCurrentPrice() * stk.getNumberOfShares();
        }
        
        //show total value
        DecimalFormat fmt = new DecimalFormat("$#,##0.00");
        lblTotalValue.setText("Total Value: "+ fmt.format(totalValue));
    }

}
